// <auto-generated />
using System;
using LoyaltyLab.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoyaltyLab.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LoyaltyLabDbContext))]
    [Migration("20260825153000_AddSagaRecovery")]
    partial class AddSagaRecovery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("LoyaltyLab.Domain.Booking.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Drift")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierReference")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Booking.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DispatchedAt", "OccurredAt");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Booking.PoisonMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PoisonedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.ToTable("PoisonMessages", (string)null);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Booking.SagaInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Checkout")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStepIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastHeartbeatAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("Status", "LastHeartbeatAt");

                    b.ToTable("SagaInstances", (string)null);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Catalog.PartnerSupplier", b =>
                {
                    b.Property<Guid>("PartnerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("TEXT");

                    b.HasKey("PartnerId", "SupplierId");

                    b.ToTable("PartnerSuppliers", (string)null);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Catalog.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Catalog.TravelOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("AvailableFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("AvailableTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NetRate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("StarRating")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxesAndFees")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId", "AvailableFrom", "AvailableTo");

                    b.ToTable("TravelOffers", (string)null);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("PartnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("PartnerId", "Operation", "Key");

                    b.ToTable("IdempotencyRecords", (string)null);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Ledger.LedgerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId", "MemberId")
                        .IsUnique()
                        .HasFilter("MemberId IS NOT NULL");

                    b.HasIndex("PartnerId", "Type")
                        .IsUnique()
                        .HasFilter("MemberId IS NULL");

                    b.ToTable("LedgerAccounts", (string)null);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Ledger.LedgerTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReversesTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("PartnerId", "OccurredAt");

                    b.ToTable("LedgerTransactions", (string)null);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Pricing.PricingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId", "Kind", "EffectiveFrom", "EffectiveTo");

                    b.ToTable("PricingRules", (string)null);

                    b.HasDiscriminator<int>("Kind");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Pricing.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaxCreditTender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberPrice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NetCostSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NetRateSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId", "MemberId", "ExpiresAt");

                    b.ToTable("Quotes", (string)null);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Tenancy.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId", "Id");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Tenancy.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditPolicy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpportunityPolicy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuotePolicy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SagaPolicy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Partners", (string)null);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Pricing.BaseMarkupRule", b =>
                {
                    b.HasBaseType("LoyaltyLab.Domain.Pricing.PricingRule");

                    b.Property<decimal>("Markup")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Pricing.BurnCapRule", b =>
                {
                    b.HasBaseType("LoyaltyLab.Domain.Pricing.PricingRule");

                    b.Property<decimal>("Cap")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Pricing.CampaignDiscountRule", b =>
                {
                    b.HasBaseType("LoyaltyLab.Domain.Pricing.PricingRule");

                    b.Property<decimal>("Adjustment")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("Adjustment");

                    b.Property<string>("CampaignCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Pricing.EligibilityExclusionRule", b =>
                {
                    b.HasBaseType("LoyaltyLab.Domain.Pricing.PricingRule");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Pricing.MarginFloorRule", b =>
                {
                    b.HasBaseType("LoyaltyLab.Domain.Pricing.PricingRule");

                    b.Property<decimal>("FloorAboveNet")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Pricing.TierAdjustmentRule", b =>
                {
                    b.HasBaseType("LoyaltyLab.Domain.Pricing.PricingRule");

                    b.Property<decimal>("Adjustment")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("Adjustment");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Booking.SagaInstance", b =>
                {
                    b.OwnsMany("LoyaltyLab.Domain.Booking.SagaStepRecord", "Steps", b1 =>
                        {
                            b1.Property<Guid>("SagaInstanceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Kind")
                                .HasMaxLength(32)
                                .HasColumnType("TEXT");

                            b1.Property<int>("Attempts")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Compensation")
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset?>("CompletedAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ExternalReference")
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.Property<string>("IdempotencyKey")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.Property<string>("LastError")
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset?>("StartedAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT");

                            b1.HasKey("SagaInstanceId", "Kind");

                            b1.ToTable("SagaSteps", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SagaInstanceId");
                        });

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Ledger.LedgerTransaction", b =>
                {
                    b.OwnsMany("LoyaltyLab.Domain.Ledger.LedgerEntry", "Entries", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("AccountId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Amount")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("AccountId");

                            b1.HasIndex("TransactionId");

                            b1.ToTable("LedgerEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
