// <auto-generated />
using System;
using LoyaltyLab.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoyaltyLab.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LoyaltyLabDbContext))]
    [Migration("20260824191024_AddPricingRules")]
    partial class AddPricingRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("LoyaltyLab.Domain.Catalog.PartnerSupplier", b =>
                {
                    b.Property<Guid>("PartnerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("TEXT");

                    b.HasKey("PartnerId", "SupplierId");

                    b.ToTable("PartnerSuppliers", (string)null);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Catalog.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Catalog.TravelOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("AvailableFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("AvailableTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NetRate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("StarRating")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxesAndFees")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId", "AvailableFrom", "AvailableTo");

                    b.ToTable("TravelOffers", (string)null);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Pricing.PricingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId", "Kind", "EffectiveFrom", "EffectiveTo");

                    b.ToTable("PricingRules", (string)null);

                    b.HasDiscriminator<int>("Kind");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Pricing.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaxCreditTender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberPrice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NetCostSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NetRateSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId", "MemberId", "ExpiresAt");

                    b.ToTable("Quotes", (string)null);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Tenancy.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId", "Id");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Tenancy.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditPolicy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpportunityPolicy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuotePolicy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SagaPolicy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Partners", (string)null);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Pricing.BaseMarkupRule", b =>
                {
                    b.HasBaseType("LoyaltyLab.Domain.Pricing.PricingRule");

                    b.Property<decimal>("Markup")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Pricing.BurnCapRule", b =>
                {
                    b.HasBaseType("LoyaltyLab.Domain.Pricing.PricingRule");

                    b.Property<decimal>("Cap")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Pricing.CampaignDiscountRule", b =>
                {
                    b.HasBaseType("LoyaltyLab.Domain.Pricing.PricingRule");

                    b.Property<decimal>("Adjustment")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("Adjustment");

                    b.Property<string>("CampaignCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Pricing.EligibilityExclusionRule", b =>
                {
                    b.HasBaseType("LoyaltyLab.Domain.Pricing.PricingRule");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Pricing.MarginFloorRule", b =>
                {
                    b.HasBaseType("LoyaltyLab.Domain.Pricing.PricingRule");

                    b.Property<decimal>("FloorAboveNet")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("LoyaltyLab.Domain.Pricing.TierAdjustmentRule", b =>
                {
                    b.HasBaseType("LoyaltyLab.Domain.Pricing.PricingRule");

                    b.Property<decimal>("Adjustment")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("Adjustment");

                    b.HasDiscriminator().HasValue(2);
                });
#pragma warning restore 612, 618
        }
    }
}
