<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LoyaltyLab.Infrastructure\LoyaltyLab.Infrastructure.csproj" />
    <ProjectReference Include="..\LoyaltyLab.Application\LoyaltyLab.Application.csproj" />
    <ProjectReference Include="..\LoyaltyLab.Domain\LoyaltyLab.Domain.csproj" />
  </ItemGroup>

</Project>
